In [1]:
import json
import pandas as pd

# Part 1: Reading and investigating data

Open up the `player_data.json` and investigate the data structure.

In [2]:
with open('player_data.json') as json_file:
    data = json.load(json_file)
    
df = pd.DataFrame()

# Part 2:  Creating the Dataframe

Create a data frame where each row corresponds to a game for each player. You must have atleast the following columns in your final dataframe:

'DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID', 'AST', 'BLK', 'DREB','Game_ID',  'MIN', 'PTS', 'REB', 'TEAM_ABBREVIATION'

*You can include additional columns in your dataframe, so you don't have to do additional work to remove other columns.*

In [3]:
for person in data:
    if len(person['GAMELOG']) == 0:
        continue
    df1 = pd.DataFrame(person, columns=['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID'], index=[0])
    df2 = pd.DataFrame(person['GAMELOG'])
    merged = pd.merge(df1, df2, left_on='PERSON_ID', right_on='Player_ID', how='outer')
    df = pd.concat([df, merged])
    
df.reset_index(drop=True, inplace=True)
df.columns

26101

Index(['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID_x', 'AST', 'BLK', 'DREB',
       'FG3A', 'FG3M', 'FG3_PCT', 'FGA', 'FGM', 'FG_PCT', 'FTA', 'FTM',
       'FT_PCT', 'GAME_DATE', 'Game_ID', 'MATCHUP', 'MIN', 'OREB', 'PF',
       'PLUS_MINUS', 'PTS', 'Player_ID', 'REB', 'SEASON_ID', 'STL',
       'TEAM_ABBREVIATION', 'TEAM_ID_y', 'TOV', 'VIDEO_AVAILABLE', 'WL'],
      dtype='object')

# Part 3: Pandas Questions

Answer the following questions

## 1 
- Find the player who scored the most points in an individual game last season.

-  Now do the same for rebounds, blocks, and assists.

In [142]:
mst_pts = df.loc[df.PTS == df.PTS.max()]
mst_rbnd = df.loc[df.REB == df.REB.max()]
mst_blks = df.loc[df.BLK == df.BLK.max()]
mst_ast = df.loc[df.AST == df.AST.max()]
print(mst_pts)

      DISPLAY_FIRST_LAST  PERSON_ID   TEAM_ID_x  AST  BLK  DREB  FG3A  FG3M  \
10323       James Harden     201935  1610612745    1    0     5    13     9
10348       James Harden     201935  1610612745    4    0     9    20     5

       FG3_PCT  FGA  ...  PTS  Player_ID  REB  SEASON_ID  STL  \
10323    0.692   34  ...   61     201935    7      22018    3
10348    0.250   38  ...   61     201935   15      22018    5

      TEAM_ABBREVIATION   TEAM_ID_y TOV  VIDEO_AVAILABLE  WL
10323               HOU  1610612745   3                1   W
10348               HOU  1610612745   5                1   W

[2 rows x 32 columns]

## 2: 

- Find the player who scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [143]:
bst_sea = df.groupby(['DISPLAY_FIRST_LAST']).agg({'PTS': 'sum', 'REB': 'sum','BLK': 'sum','AST': 'sum'})
mst_pts_sea = bst_sea.loc[bst_sea['PTS'] == bst_sea['PTS'].max()]
mst_reb_sea = bst_sea.loc[bst_sea['REB'] == bst_sea['REB'].max()]
mst_BLK_sea = bst_sea.loc[bst_sea['BLK'] == bst_sea['BLK'].max()]
mst_AST_sea = bst_sea.loc[bst_sea['AST'] == bst_sea['AST'].max()]
print(mst_reb_sea)

                     PTS   REB  BLK  AST
DISPLAY_FIRST_LAST
Andre Drummond      1370  1232  138  112

## 3:
How many players played in at least 82 games last season?

In [146]:
games_sea = df['DISPLAY_FIRST_LAST'].value_counts()
more82 = len(games_sea.loc[df['DISPLAY_FIRST_LAST'].value_counts() >= 82])
more82

Reggie Jackson              82
Mikal Bridges               82
Patty Mills                 82
Montrezl Harrell            82
Kentavious Caldwell-Pope    82
Bradley Beal                82
Justin Holiday              82
DeAndre' Bembry             82
Tobias Harris               82
Joe Ingles                  82
Buddy Hield                 82
Shai Gilgeous-Alexander     82
Collin Sexton               82
Bam Adebayo                 82
Bryn Forbes                 82
Royce O'Neale               82
Cory Joseph                 82
Kemba Walker                82
Monte Morris                82
Mason Plumlee               82
PJ Tucker                   82
Name: DISPLAY_FIRST_LAST, dtype: int64

## 4: 
- Find which team scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [222]:
bst_team = df.groupby(['TEAM_ABBREVIATION']).agg({'PTS': 'sum', 'REB': 'sum','BLK': 'sum','AST': 'sum'})
mst_pts_team = bst_team.loc[bst_team['PTS'] == bst_team['PTS'].max()]
#same as question 2

                    PTS   REB  BLK   AST
TEAM_ABBREVIATION
MIL                9686  4078  486  2136

## 5:
Which team had the most players play for them last season?

In [223]:
play_team = df.groupby(by='TEAM_ABBREVIATION').agg({'DISPLAY_FIRST_LAST': 'nunique'}) # can use nunique alone and return all the columns
inclusive_t = play_team.loc[play_team.DISPLAY_FIRST_LAST == play_team.DISPLAY_FIRST_LAST.max()]
inclusive_t

                   DISPLAY_FIRST_LAST
TEAM_ABBREVIATION
MEM                                28

## 6:
- Did any players play for more than one team last year?

- What is the most number of teams a player played for last season?

## 7:

Find the player who scored the least amount of points while playing in at least 40 games last season.

In [29]:
players = df.groupby(['DISPLAY_FIRST_LAST']).agg({'DISPLAY_FIRST_LAST': 'count', 'PTS': 'sum'})
psble_players = players.loc[players.DISPLAY_FIRST_LAST > 40]
worse_player = psble_players.loc[psble_players.PTS == psble_players.PTS.min()]
worse_player

                     DISPLAY_FIRST_LAST  PTS  REB  BLK  AST
DISPLAY_FIRST_LAST
Sindarius Thornwell                  64   62   44    7   18

# Part 4: Pandas and Probability

## 8: 

What is the probability that a random player had a game where they scored more than 40 points?

In [76]:
# get number of times where player had more than 40 points in a game, divide by number of games.

total_games = len(df.PTS)
over40 = len(df.loc[df.PTS > 40])
prob40 = over40/total_games
prob40

0.004214397915788667

## 9:

What is the probability that a randomly selected player from last season would average more than 20 points per game?

In [73]:
# sample is get each player's pts avg, event is pts avg above 20
player_sum_count = df.groupby(['DISPLAY_FIRST_LAST']).agg({'PTS': 'sum', 'DISPLAY_FIRST_LAST': 'count'})

#create a new array for the avg points for each player
avg_pts = player_sum_count.PTS / player_sum_count['DISPLAY_FIRST_LAST'] 

# bool that returns only players with pt avg above 20
avg_pts_bool = avg_pts > 20
avg_pts20 = len(avg_pts[avg_pts_bool])/ len(avg_pts)

print(f'{avg_pts20}, thanks pandas and arrays')

0.062264150943396226, thanks pandas and MATLAB type arrays

# Advanced Questions

## 10: 
Find the player who scored the least amount of points while playing in at least 40 games and averageing at least 15 minutes per game last season.

In [108]:
#group what I need - average time played, how many apearnaces and points
player_count = df.groupby(['DISPLAY_FIRST_LAST']).agg({'DISPLAY_FIRST_LAST': 'count', 'PTS': 'sum', 'MIN': 'mean'})

# get new data frame for games where players played more than 15 minutes
over15m = player_count.loc[player_count.MIN > 15]

# from that list get only the list of players that played over 40 games
over40g = over15m.loc[over15m['DISPLAY_FIRST_LAST'] > 40]

worse_player15 = over40g.loc[over40g.PTS  == over40g.PTS.min()]
# find the player scored least
worse_player15.head()

                    DISPLAY_FIRST_LAST  PTS        MIN
DISPLAY_FIRST_LAST
Tyson Chandler                      55  173  15.927273

## 11: 
Which player scored the largest share of points for their team throughout the season.

In [229]:
#Total points scored for every team
score_per_player = df.groupby(['TEAM_ABBREVIATION','DISPLAY_FIRST_LAST']).agg({'PTS': 'sum'})
# score_most_team = df.groupby(['TEAM_ABBREVIATION']).agg({'PTS': 'sum'})


results = score_per_player.groupby(level=0).apply(lambda x: x / float(x.sum())) # still need to sort
results

                                           PTS
TEAM_ABBREVIATION DISPLAY_FIRST_LAST
ATL               Alex Len            0.091887
                  Alex Poythress      0.011513
                  BJ Johnson          0.002260
                  Daniel Hamilton     0.006133
                  DeAndre' Bembry     0.073919
                  Dewayne Dedmon      0.074564
                  Deyonta Davis       0.003873
                  Isaac Humphries     0.001614
                  Jaylen Adams        0.011620
                  Jeremy Lin          0.058748
                  John Collins        0.127824
                  Jordan Sibert       0.000323
                  Justin Anderson     0.019152
                  Kent Bazemore       0.083818
                  Kevin Huerter       0.078223
                  Miles Plumlee       0.008608
                  Omari Spellman      0.029266
                  Taurean Prince      0.079836
                  Trae Young          0.166667
                  Tyler Dorsey        0.009684
                  Tyler Zeller        0.000000
                  Vince Carter        0.060469
BKN               Alan Williams       0.001956
                  Allen Crabbe        0.044872
                  Caris LeVert        0.059431
                  D'Angelo Russell    0.186006
                  DeMarre Carroll     0.080834
                  Dzanan Musa         0.002064
                  Ed Davis            0.051282
                  Jared Dudley        0.031182
...                                        ...
UTA               Royce O'Neale       0.046501
                  Rudy Gobert         0.140159
                  Thabo Sefolosha     0.020740
                  Tony Bradley        0.001856
                  Tyler Cavanaugh     0.000982
WAS               Austin Rivers       0.022460
                  Bobby Portis        0.042781
                  Bradley Beal        0.224492
                  Chasson Randle      0.028984
                  Devin Robinson      0.005027
                  Dwight Howard       0.012299
                  Gary Payton II      0.001176
                  Ian Mahinmi         0.014866
                  Jabari Parker       0.040000
                  Jason Smith         0.004706
                  Jeff Green          0.101176
                  John Jenkins        0.000642
                  John Wall           0.070909
                  Jordan McRae        0.017112
                  Kelly Oubre Jr.     0.039893
                  Markieff Morris     0.041818
                  Okaro White         0.000000
                  Otto Porter Jr.     0.055401
                  Ron Baker           0.000000
                  Sam Dekker          0.024599
                  Thomas Bryant       0.081070
                  Tomas Satoransky    0.075829
                  Trevor Ariza        0.064706
                  Troy Brown Jr.      0.026524
                  Wesley Johnson      0.003529

[622 rows x 1 columns]

## 12:

What is the probability that a randomly selected player had at least one game in which they scored 40 points last season.

In [ ]:
# your code here

## 13: 

A double-double is when a player records for any of the two follow categories: points, rebounds, assists, steals, or blocks. 
What is the probability that a randomly selected player had a double-double in a game last season?

In [232]:
full_stats = df.groupby(['DISPLAY_FIRST_LAST']).agg({'DISPLAY_FIRST_LAST': 'count', 'PTS': 'mean', 'REB': 'mean', 'AST': 'mean', 'BLK': 'mean', 'STL': 'mean'})
full_stats

,DISPLAY_FIRST_LAST,PTS,REB,AST,BLK,STL
DISPLAY_FIRST_LAST,,,,,,
Aaron Gordon,78,15.974359,7.358974,3.705128,0.717949,0.730769
Aaron Holiday,50,5.880000,1.340000,1.740000,0.260000,0.420000
Abdel Nader,61,3.950820,1.901639,0.327869,0.196721,0.327869
Al Horford,68,13.602941,6.735294,4.161765,1.264706,0.867647
Al-Farouq Aminu,81,9.382716,7.530864,1.283951,0.407407,0.839506
Alan Williams,5,3.600000,3.800000,0.600000,0.000000,0.200000
Alec Burks,64,8.765625,3.671875,2.000000,0.328125,0.609375
Alex Abrines,31,5.322581,1.548387,0.645161,0.193548,0.548387
Alex Caruso,25,9.160000,2.680000,3.080000,0.360000,0.960000
Alex Len,77,11.090909,5.506494,1.116883,0.896104,0.350649
Alex Poythress,21,5.095238,3.619048,0.809524,0.476190,0.190476
Alfonzo McKinnie,72,4.680556,3.430556,0.430556,0.208333,0.250000
Alize Johnson,14,0.928571,1.357143,0.071429,0.214286,0.071429
Allen Crabbe,43,9.604651,3.441860,1.069767,0.302326,0.534884
Allonzo Trier,64,10.859375,3.078125,1.859375,0.218750,0.437500
Amile Jefferson,12,2.250000,1.750000,0.250000,0.250000,0.250000
Amir Johnson,51,3.941176,2.882353,1.176471,0.254902,0.313725
Andre Drummond,79,17.341772,15.594937,1.417722,1.746835,1.721519
Andre Iguodala,68,5.720588,3.705882,3.176471,0.750000,0.897059
Andre Ingram,4,0.000000,0.500000,0.000000,0.000000,0.250000
Andrew Bogut,11,3.545455,5.000000,1.000000,0.727273,0.272727
Andrew Harrison,17,3.176471,1.176471,1.411765,0.117647,0.235294
Andrew Wiggins,73,18.095890,4.821918,2.520548,0.657534,0.958904
Anfernee Simons,20,3.750000,0.650000,0.650000,0.000000,0.050000
Angel Delgado,2,1.500000,2.000000,0.000000,0.000000,0.500000
Ante Zizic,59,7.779661,5.423729,0.898305,0.372881,0.220339
Anthony Davis,56,25.928571,12.000000,3.892857,2.410714,1.571429
Anthony Tolliver,65,5.015385,2.723077,0.707692,0.323077,0.261538
Antonio Blakeney,57,7.333333,1.859649,0.736842,0.157895,0.210526
Aron Baynes,51,5.568627,4.705882,1.117647,0.666667,0.235294
...,...,...,...,...,...,...
Tyler Zeller,6,7.666667,4.000000,0.666667,0.500000,0.166667
Tyreke Evans,69,10.231884,2.913043,2.405797,0.260870,0.840580
Tyrone Wallace,62,3.516129,1.629032,0.677419,0.112903,0.338710
Tyson Chandler,55,3.145455,5.581818,0.672727,0.418182,0.381818
Tyus Jones,68,6.882353,1.970588,4.808824,0.073529,1.191176
Udonis Haslem,10,2.500000,2.700000,0.200000,0.000000,0.000000
Victor Oladipo,36,18.750000,5.611111,5.166667,0.305556,1.666667
Vince Carter,76,7.394737,2.552632,1.144737,0.355263,0.578947
Vincent Edwards,2,1.500000,1.000000,0.000000,0.000000,0.000000
Wade Baldwin IV,16,1.875000,0.937500,0.750000,0.125000,0.062500
Walter Lemon Jr.,6,14.333333,4.500000,5.000000,0.166667,1.833333
Wayne Ellington,53,10.283019,2.018868,1.358491,0.113208,1.018868
Wayne Selden,75,6.853333,2.400000,1.453333,0.173333,0.440000
Wendell Carter Jr.,44,10.340909,6.977273,1.772727,1.318182,0.590909
Wes Iwundu,68,4.985294,2.705882,1.073529,0.323529,0.411765
Wesley Johnson,38,3.368421,1.894737,0.605263,0.315789,0.368421
Wesley Matthews,69,12.173913,2.463768,2.318841,0.246377,0.782609
Will Barton,43,11.488372,4.627907,2.883721,0.511628,0.418605
Willie Cauley-Stein,81,11.913580,8.370370,2.395062,0.629630,1.185185
Willy Hernangomez,58,7.258621,5.362069,1.034483,0.344828,0.275862
Wilson Chandler,51,5.980392,4.215686,1.607843,0.411765,0.490196
Yante Maten,2,1.000000,1.500000,0.000000,0.000000,0.500000
Yogi Ferrell,71,5.915493,1.535211,1.929577,0.056338,0.507042
Yuta Watanabe,15,2.600000,2.066667,0.533333,0.066667,0.266667
Zach Collins,77,6.649351,4.207792,0.922078,0.857143,0.324675
Zach LaVine,63,23.682540,4.666667,4.492063,0.412698,0.952381
Zach Lofton,1,0.000000,0.000000,0.000000,0.000000,1.000000
Zaza Pachulia,68,3.926471,3.897059,1.338235,0.250000,0.455882
Zhaire Smith,6,6.666667,2.166667,1.666667,0.333333,0.333333
Zhou Qi,1,2.000000,0.000000,0.000000,0.000000,0.000000

## 14:

What is the probability that a randomnly selected game had a player record a triple-double in that game?

In [ ]:
#your code here

# Part 5: Super Duper Challenge

## 15:

How many players last season averaged more points per game than their career average?